config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#omniauth_callback'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy] do
    collection do
    end
  end
  resource :home, only: [:index]

  resources :linked_accounts, only: [:destroy] do
    collection do
      get :dropbox
      get :dropbox_callback
      get :box
      get :box_callback
      post :upload_file
    end
  end

  get 'items/list/*specs', controller: 'items', action: 'list', as: "specs"

  match "*path", to: "home#routing_error", via: :all

end

app/models/linked_account.rb
class LinkedAccount < ActiveRecord::Base
  belongs_to :user

  def client
    if provider == "dropbox"
      dbsession = DropboxSession.deserialize(self.access_token)
      return DropboxClient.new(dbsession, DROPBOX_APP_MODE)
    else
      session = RubyBox::Session.new({client_id: BOX_APP_KEY, client_secret: BOX_APP_KEY_SECRET, access_token: access_token})
      return RubyBox::Client.new(session)
    end
  end

  def account_info
    if provider == "dropbox"
      return client.account_info()
    else
      return client.me().as_json
    end
  end

  def display_name
    if provider == "dropbox"
      return account_info["display_name"]
    else
      return account_info["name"]
    end
  end

  def space_available
    if provider == "dropbox"
      quota_info = account_info["quota_info"]
      return (quota_info["quota"] - quota_info["normal"] - quota_info["shared"])
    else
      return client.me().as_json["space_amount"]
    end
  end

  def list_of_files
    if provider == "dropbox"
      root_metadata = client.metadata('/')
      return root_metadata["contents"] if root_metadata.has_key?("contents")
      return []
    else
      return client.root_folder.items.as_json
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :linked_accounts, :dependent => :destroy

  has_secure_password(validations: false)

  validates :email, presence: true, unless: :facebook_user?
  validates :password, presence: true, unless: :facebook_user?
  validates :email, format: {:with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, :message => '^Email is invalid'}, unless: :facebook_user?
  validates :email, uniqueness: {:message => '^Email / password is invalid'}, unless: :facebook_user?

  # validates_confirmation_of :password, :if => :password_present?
  # validates_presence_of     :password, :on => :create, :unless => :facebook_user?

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def name_or_email
    self.name || self.email
  end

  # private

  def facebook_user?
    provider != nil && uid != nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  rescue_from RubyBox::AuthError, with: :deny_access

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private

  def deny_access
    if current_user
      account = current_user.linked_accounts.where(provider: "box").first
      flash[:error] = "Authentication expired: #{account.provider}"
      account.destroy
    else
      flash[:error] = "Authentication expired:"
    end
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @link_accounts = current_user.linked_accounts
    else
      render :partial=> "/sessions/sign_in", :layout => "application"
    end
  end

  def routing_error
    redirect_to root_path
  end
end

app/controllers/linked_accounts_controller.rb
class LinkedAccountsController < ApplicationController
  include FileUpload

  def dropbox
    dbsession = DropboxSession.new(DROPBOX_APP_KEY, DROPBOX_APP_KEY_SECRET)
    session[:dropbox_session] = dbsession.serialize
    redirect_to dbsession.get_authorize_url(url_for(:action => 'dropbox_callback'))
  end

  def dropbox_callback
    dbsession = DropboxSession.deserialize(session[:dropbox_session])
    dbsession.get_access_token #we've been authorized, so now request an access_token
    linked_account = current_user.linked_accounts.where({:provider => "dropbox", :uid => params[:uid]}).first_or_initialize
    linked_account.access_token = dbsession.serialize
    if linked_account.save
      session.delete :dropbox_session
      flash[:success] = t(:aurization_success, :name => "dropbox")
    else
      flash[:error] = linked_account.errors.full_messages.first
    end
  rescue DropboxAuthError => e
    flash.now[:error] = e.message
  rescue OAuth2::Error => e
    flash.now[:error] = e.message
  ensure
    redirect_to root_path
  end

  def box
    boxsession = RubyBox::Session.new({client_id: BOX_APP_KEY, client_secret: BOX_APP_KEY_SECRET})
    session[:box_session] = boxsession
    authorize_url = boxsession.authorize_url(url_for(:action => 'box_callback'))
    redirect_to authorize_url
  end

  def box_callback
    boxsession = RubyBox::Session.new({client_id: BOX_APP_KEY, client_secret: BOX_APP_KEY_SECRET})
    token = boxsession.get_access_token(params["code"])
    linked_account = current_user.linked_accounts.where({:provider => "box"}).first_or_initialize
    linked_account.access_token = token.token
    if linked_account.save
      session.delete :box_session
      flash[:success] = t(:aurization_success, :name => "box")
    end
  rescue OAuth2::Error => e
    flash.now[:error] = e.message
  ensure
    redirect_to root_path
  end

  def upload_file
    file = params[:uploaded_file]
    if file.present?
      account = current_user.linked_accounts.sort_by(&:space_available).last
      result = fileupload(file, account)
      flash[result[:key].to_sym] = result[:message]
    else
      flash[:error] = t(:file_select_error)
    end
  rescue => e
    flash[:error] = t(:something_wrong_with_file_upload, :filename => (file ? file.original_filename : nil))
  ensure
    redirect_to root_path
  end

  def destroy
    linked_account = LinkedAccount.find(params[:id])
    linked_account.destroy
    flash[:success] = t(:account_disconnected, :provider => linked_account.provider)
  rescue ActiveRecord::RecordNotFound
    flash[:error] = t(:something_wrong_with_account_destroy)
  ensure
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.find_by(:email => params[:user][:email]).try(:authenticate, params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      @user = User.new(allowed_parameters)
      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash.now[:error] = @user.errors.full_messages.first
        # render :new
      end
      # flash.now[:error] = 'Email / password is invalid'
      # render :new
    end
  end

  def omniauth_callback
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def oauth_failure
    flash[:error] = t(:access_denied)
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:message] = t(:signout)
    redirect_to root_path
  end

  private

  def allowed_parameters
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def show_account_button(accounts = [], account_name)
    linked_account = accounts.find{|account| account.provider == account_name}
    if linked_account
      button_tag(image_tag("#{account_name}.png", :size => "30x30") + " - " + linked_account.display_name + raw("<br />") + link_to("Disconnect", linked_account_path(linked_account.id), :method => "DELETE", :data => {:confirm => "Are you sure to disconnect from #{account_name}"}), :class => "btn btn-large")
    else
      link_to(account_name.titlecase, "/linked_accounts/#{account_name}", :class => "btn btn-primary btn-large", :onClick => "$.blockUI();")
    end
  end
end

app/helpers/linked_accounts_helper.rb
module LinkedAccountsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div class="hero-unit clearfix ">
  <div style="width:50%; float: left; border-right: dotted thin">
    <h1>Link Accounts</h1>
    <p>Connect Cloud storage accounts.</p>
    <p>
      <% ["dropbox", "box"].each do |account_name| %>
          <%= show_account_button(@link_accounts, account_name)%>
      <% end %>
    </p>
  </div>

  <div style="width: 48%; float: right;">
    <h3>Upload File:</h3>
    <%= form_tag(upload_file_linked_accounts_path, :multipart => true, :onSubmit => "$.blockUI();") do %>
        <p>
          Click on Upload after click on Browse...<br />
          <%= file_field_tag :uploaded_file, :class => "file" %>
        </p>
        <%= submit_tag("Upload", :class => "btn btn-inverse")%>
    <% end %>
  </div>
</div>


<ul class="nav nav-tabs cols_2">
  <li class="active"><a href="#dropbox" data-toggle="tab">Dropbox</a></li>
  <li><a href="#box" data-toggle="tab">Box</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="dropbox">
    <h2>List of Files:</h2>
    <% linked_account = @link_accounts.find{|account| account.provider == "dropbox"} %>
    <% if linked_account %>
        <p>Space Available: <%= number_to_human_size(linked_account.space_available) %></p>
        <% linked_account.list_of_files.each do |file| %>
            <p><%= raw("<strong>Folder: </strong>") if file["is_dir"] %><%= file["path"] %></p>
        <% end %>
    <% else %>
        <p>No Files to list</p>
    <% end %>
  </div>

  <div class="tab-pane" id="box">
    <h2>List of Files:</h2>
    <% linked_account = @link_accounts.find{|account| account.provider == "box"} %>
    <% if linked_account %>
        <p>Space Available: <%= number_to_human_size(linked_account.space_available) %></p>
        <% linked_account.list_of_files.each do |file| %>
            <p><%= raw("<strong>Folder: </strong>") if file["type"] == "folder" %><%= file["name"] %></p>
        <% end %>
    <% else %>
        <p>No Files to list</p>
    <% end %>
  </div><!-- @end #empty -->
</div>
<script type="text/javascript">
    $("#uploaded_file").fileinput({showUpload: false, maxFileCount: 10, mainClass: "input-group-lg"});
</script>

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FooShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <%= render :partial => "/layouts/header" %>
  <div class="container">
    <p>
    <% flash.each do |name, msg| %>
        <%= content_tag :div, :class => "alert fade in alert-#{name}" do %>
            <button type="button" data-dismiss="alert" class="close">×</button>
            <%= msg  %>
        <% end %>
    <% end %>
    </p>
    <%= yield %>
    <hr />
    <%= render :partial => "/layouts/footer" %>
  </div> <!-- /container -->
</div>
</body>
</html>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; Company <%= Date.today.year %></p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">Foo Share</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><a href="/">Home</a></li>
        </ul>
        <div class="navbar-form pull-right">
          <% if current_user %>
              <span style="color: #ffffff;">Signed in as <%= image_tag("http://graph.facebook.com/#{current_user.uid}/picture") if current_user.facebook_user? %> <strong><%= current_user.name_or_email %></strong>&nbsp;</span>
              <%= link_to "Sign out", signout_path, :class => "btn" %>
          <% end %>
        </div>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<%= render :partial => "/layouts/application" %>